services:
  database:
    image: mariadb:11.6.2
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./docker-mysql-init/:/docker-entrypoint-initdb.d
